name: 'Apply Infrastructure'

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:    
  terraform-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws-network-infra/examples/dev
  
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate 
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan 
        id: plan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        run: terraform plan -refresh=false -no-color -parallelism=1

      # - name: Terraform Apply
      #   id: apply
      #   env:
      #     TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #   run: terraform apply -auto-approve -no-color